name: anaconda_packaging_utils

dependencies:
  # Python/plugins
  - black
  - isort
  - mypy
  - python >=3.11
  - pytest
  - pytest-cov
  - pytest-xdist
  - pylint
  - pip
  # Python libraries
    # <TODO add libraries used by source code here>
  # Other
  # TODO fix: Pin conda version when this PR gets released
  #   https://github.com/conda/conda/pull/13385
  - conda
  - conda-build
  - pre-commit
  - make
